project_name: rocket
builds:
  - main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
    artifacts:
      - binary
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
release:
  github:
    owner: muhfaris
    name: rocket
    draft: false
    prerelease: "{{ .Tag | contains `-rc` }}"
changelog:
  use: true
