openapi: 3.0.0
info:
  title: Partner API
  version: 1.0.0
servers:
  - url: http://{{local}}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Register Partner
paths:
  /register/partners:
    post:
      operationId: GetPartners::PartnerSvc
      tags:
        - Register Partner
      summary: Register new account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                fullname: ahmad jomkoleq 100
                password: ahmadjomkoleq!1
                confirm_password: ahmadjomkoleq!1
                email: ahmad.jomkoleq+1004@gmail.com
                accepted_tnc: true
      security:
        - noauthAuth: []
      responses:
        "201":
          description: Created
          headers:
            Date:
              schema:
                type: string
                example: Thu, 28 Sep 2023 13:35:31 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "368"
            Vary:
              schema:
                type: string
                example: Origin
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
          content:
            application/json:
              schema:
                type: object
              example:
                response:
                  data:
                    id: 01HBE00X5165PB9M5687PB12GY
                    fullname: ahmad jomkoleq
                    email: ahmad.jomkoleq@gmail.com
                    status: waiting_verification
                    created_at: "2023-09-28T20:35:32.001775913+07:00"
                    updated_at: "2023-09-28T20:35:32.001775913+07:00"
                message: successfully created new customer account
                code: Created
                status_code: 201
                latency: 145.235588ms
        "400":
          description: Bad Request
          headers:
            Date:
              schema:
                type: string
                example: Mon, 27 Mar 2023 16:04:41 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "171"
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 400 - password and confirm password not match
                  value:
                    message: the Password must be equal with ConfirmPassword
                    code: Bad Request
                    status_code: 400
                    error: the Password must be equal with ConfirmPassword
                    latency: ""
                example-1:
                  summary: 400 - invalid email
                  value:
                    message: the Email not valid
                    code: Bad Request
                    status_code: 400
                    error: the Email not valid
                    latency: ""
                example-2:
                  summary: 400 - accepten n condition false
                  value:
                    message: AcceptedTnC is a required field
                    code: Bad Request
                    status_code: 400
                    error: AcceptedTnC is a required field
                    latency: 174.41µs
  /register/partners/{partner_id}:
    get:
      operationId: GetDetailPartner::PartnerSvc
      x-route-group: partnerGroup::/api
      tags:
        - Register Partner
      summary: Get detail partner account
      x-parameters-name: DetailPartner
      parameters:
        - name: partner_id
          in: path
          schema:
            type: string
          required: true
          example: "{{partner_id}}"
      security:
        - noauthAuth: []
      responses:
        "201":
          description: Created
          headers:
            Date:
              schema:
                type: string
                example: Thu, 28 Sep 2023 13:35:31 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "368"
            Vary:
              schema:
                type: string
                example: Origin
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
          content:
            application/json:
              schema:
                type: object
              example:
                response:
                  data:
                    id: 01HBE00X5165PB9M5687PB12GY
                    fullname: ahmad jomkoleq
                    email: ahmad.jomkoleq@gmail.com
                    status: waiting_verification
                    created_at: "2023-09-28T20:35:32.001775913+07:00"
                    updated_at: "2023-09-28T20:35:32.001775913+07:00"
                message: successfully created new customer account
                code: Created
                status_code: 201
                latency: 145.235588ms
        "400":
          description: Bad Request
          headers:
            Date:
              schema:
                type: string
                example: Mon, 27 Mar 2023 16:04:41 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "171"
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 400 - password and confirm password not match
                  value:
                    message: the Password must be equal with ConfirmPassword
                    code: Bad Request
                    status_code: 400
                    error: the Password must be equal with ConfirmPassword
                    latency: ""
                example-1:
                  summary: 400 - invalid email
                  value:
                    message: the Email not valid
                    code: Bad Request
                    status_code: 400
                    error: the Email not valid
                    latency: ""
                example-2:
                  summary: 400 - accepten n condition false
                  value:
                    message: AcceptedTnC is a required field
                    code: Bad Request
                    status_code: 400
                    error: AcceptedTnC is a required field
                    latency: 174.41µs
    patch:
      operationId: UpdatePartnerHandler::PartnerSvc
      x-route-group: partnerGroup::/api
      tags:
        - Register Partner
      parameters:
        - name: partner_id
          in: path
          schema:
            type: string
          required: true
          example: "{{partner_id}}"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-properties-name: UpdatePartner
              properties:
                fullname:
                  type: string
                email:
                  type: string
      responses:
        200:
          description: ""
