services:
	docker compose down -v --remove-orphans
	docker compose up -d
init:
	go mod tidy
	go mod vendor -v
run:
	go run main.go rest
build:
	go build -o $(GOPATH)/bin/{{.AppName}} .
start: services init run

.PHONY: services
