name: Release with Goreleaser
on:
  push:
    tags:
      - "v*" # Trigger only on tags starting with "v"
jobs:
  release:
    name: Goreleaser Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Install Goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
      - name: Run Goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: goreleaser release --rm-dist
