name: Run Go Application
on:
  pull_request:
    branches:
      - master
jobs:
  run-go-app:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22" # Update to your required Go version
      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy
      # Step 4: Run the application
      - name: Run Go Application
        run: go run main.go
      # Optional: Verify the run succeeded
      - name: Verify application execution
        if: success()
        run: go run main.go new
