name: Run Go Application
on:
  pull_request:
    branches:
      - master
jobs:
  run-go-app:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22" # Update to your required Go version
      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy
      # Step 4: Run the application
      - name: Run Go Application
        run: go run main.go
      - name: Install go import
        run: go install golang.org/x/tools/cmd/goimports@latest
      # Optional: Verify the run succeeded
      - name: Verify application execution basic
        if: success()
        run: |
          rm -rf basic
          go run main.go new -c rocket-basic.yaml
          cd basic && go mod tidy && go mod vendor
      - name: Verify application execution cache redis
        if: success()
        run: |
          rm -rf cacher
          go run main.go new -c rocket-cache.yaml
          cd cacher && go mod tidy && go mod vendor
      - name: Verify application execution database mongo
        if: success()
        run: |
          rm -rf mongodb
          go run main.go new -c rocket-database-mongo.yaml
          cd mongodb && go mod tidy && go mod vendor
      - name: Verify application execution database mysql
        if: success()
        run: |
          rm -rf mysql
          go run main.go new -c rocket-database-mysql.yaml
          cd mysql && go mod tidy && go mod vendor
      - name: Verify application execution pg
        if: success()
        run: |
          rm -rf pg
          go run main.go new -c rocket-database-pg.yaml
          cd pq && go mod tidy && go mod vendor
      - name: Verify application execution docker
        if: success()
        run: |
          rm -rf dcc
          go run main.go new -c rocket-docker.yaml
          cd dcc && go mod tidy && go mod vendor
      - name: Verify application execution all
        if: success()
        run: |
          go run main.go new -c rocket.yaml
          cd r1 && go mod tidy && go mod vendor
      - name: Remove all dummy data
        if: success()
        run: |
          rm -rf basic cacher mongodb mysql pg dcc r1
