name: Run Go Application
on:
  pull_request:
    branches:
      - master
jobs:
  run-go-app:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22" # Update to your required Go version
      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy
      # Step 4: Run the application
      - name: Run Go Application
        run: go run main.go
      - name: Install go import
        run: go install golang.org/x/tools/cmd/goimports@latest
      # Optional: Verify the run succeeded
      - name: Verify application execution basic
        if: success()
        run: go run main.go new -c rocket-basic.yaml
      - name: Verify application execution cache redis
        if: success()
        run: go run main.go new -c rocket-cache.yaml
      - name: Verify application execution database mongo
        if: success()
        run: go run main.go new -c rocket-database-mongo.yaml
      - name: Verify application execution database mysql
        if: success()
        run: go run main.go new -c rocket-database-mysql.yaml
      - name: Verify application execution pg
        if: success()
        run: go run main.go new -c rocket-database-pg.yaml
      - name: Verify application execution docker
        if: success()
        run: go run main.go new -c rocket-docker.yaml
      - name: Verify application execution all
        if: success()
        run: go run main.go new -c rocket.yaml
